export const TILE_SIZE_WORLD = 32;

export const CHUNK_SIZE_TILES = 32;

export const CHUNK_TILE_COUNT = CHUNK_SIZE_TILES * CHUNK_SIZE_TILES;

export const CHUNK_SIZE_WORLD = TILE_SIZE_WORLD * CHUNK_SIZE_TILES;
